# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Facultate\Laborator\AI\lab3\lab3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 861, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelCurent = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelCurent.setObjectName("labelCurent")
        self.verticalLayout_3.addWidget(self.labelCurent)
        self.displayCurrent = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.displayCurrent.setObjectName("displayCurrent")
        self.verticalLayout_3.addWidget(self.displayCurrent)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.lineFitness = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineFitness.setReadOnly(True)
        self.lineFitness.setObjectName("lineFitness")
        self.horizontalLayout.addWidget(self.lineFitness)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelCurentHC = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelCurentHC.setObjectName("labelCurentHC")
        self.verticalLayout_4.addWidget(self.labelCurentHC)
        self.displayCurrentHC = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.displayCurrentHC.setObjectName("displayCurrentHC")
        self.verticalLayout_4.addWidget(self.displayCurrentHC)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.lineFitnessHC = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineFitnessHC.setReadOnly(True)
        self.lineFitnessHC.setObjectName("lineFitnessHC")
        self.horizontalLayout_2.addWidget(self.lineFitnessHC)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.individualSize = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.individualSize.setObjectName("individualSize")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.individualSize)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.noIterations = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.noIterations.setObjectName("noIterations")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.noIterations)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.populationSize = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.populationSize.setObjectName("populationSize")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.populationSize)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.mutationProb = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.mutationProb.setObjectName("mutationProb")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mutationProb)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.reproductionRate = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.reproductionRate.setObjectName("reproductionRate")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.reproductionRate)
        self.buttonStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonStart.setMinimumSize(QtCore.QSize(200, 0))
        self.buttonStart.setObjectName("buttonStart")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.buttonStart)
        self.buttonStop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonStop.setObjectName("buttonStop")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.buttonStop)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.statusEvo = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.statusEvo.setReadOnly(True)
        self.statusEvo.setObjectName("statusEvo")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.statusEvo)
        self.buttonStatistics = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonStatistics.setMinimumSize(QtCore.QSize(200, 0))
        self.buttonStatistics.setObjectName("buttonStatistics")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.buttonStatistics)
        self.buttonShowStats = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonShowStats.setMinimumSize(QtCore.QSize(200, 0))
        self.buttonShowStats.setObjectName("buttonShowStats")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.buttonShowStats)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.individualSizeHC = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.individualSizeHC.setObjectName("individualSizeHC")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.individualSizeHC)
        self.startHCdef = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startHCdef.setMinimumSize(QtCore.QSize(200, 0))
        self.startHCdef.setObjectName("startHCdef")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.startHCdef)
        self.buttonStopHC = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonStopHC.setObjectName("buttonStopHC")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.buttonStopHC)
        self.startHCevo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startHCevo.setMinimumSize(QtCore.QSize(200, 0))
        self.startHCevo.setObjectName("startHCevo")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.startHCevo)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.statusHC = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.statusHC.setReadOnly(True)
        self.statusHC.setObjectName("statusHC")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.statusHC)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.gridLayout.addLayout(self.formLayout_3, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Artificial Inteligence"))
        self.labelCurent.setText(_translate("MainWindow", "Current Best:"))
        self.label_10.setText(_translate("MainWindow", "Fitness:"))
        self.labelCurentHC.setText(_translate("MainWindow", "Current Best:"))
        self.label_11.setText(_translate("MainWindow", "Fitness:"))
        self.label_12.setText(_translate("MainWindow", "Solve using evolutionary"))
        self.label_6.setText(_translate("MainWindow", "Individual Size:"))
        self.individualSize.setText(_translate("MainWindow", "4"))
        self.label.setText(_translate("MainWindow", "Number of iterations:"))
        self.noIterations.setText(_translate("MainWindow", "10000"))
        self.label_2.setText(_translate("MainWindow", "Population Size:"))
        self.populationSize.setText(_translate("MainWindow", "100"))
        self.label_3.setText(_translate("MainWindow", "Mutation Probability:"))
        self.mutationProb.setText(_translate("MainWindow", "0.5"))
        self.label_4.setText(_translate("MainWindow", "Reproduction Rate:"))
        self.reproductionRate.setText(_translate("MainWindow", "0.5"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))
        self.label_8.setText(_translate("MainWindow", "Status:"))
        self.statusEvo.setText(_translate("MainWindow", "Unstarted"))
        self.buttonStatistics.setText(_translate("MainWindow", "Calculate Statistics"))
        self.buttonShowStats.setText(_translate("MainWindow", "Show Statistics"))
        self.label_17.setText(_translate("MainWindow", "Statistics:"))
        self.label_5.setText(_translate("MainWindow", "Solve using hill climbing"))
        self.label_7.setText(_translate("MainWindow", "Individual Size:"))
        self.individualSizeHC.setText(_translate("MainWindow", "4"))
        self.startHCdef.setText(_translate("MainWindow", "Start with random individual"))
        self.buttonStopHC.setText(_translate("MainWindow", "Stop"))
        self.startHCevo.setText(_translate("MainWindow", "Start with previous evolution result"))
        self.label_9.setText(_translate("MainWindow", "Status:"))
        self.statusHC.setText(_translate("MainWindow", "Unstarted"))
        self.label_13.setText(_translate("MainWindow", "Autor:"))
        self.label_14.setText(_translate("MainWindow", "Ancau Adrian-Ilie"))
        self.label_15.setText(_translate("MainWindow", "Group:"))
        self.label_16.setText(_translate("MainWindow", "921/1"))

